openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: A simple API to manage users.

servers:
  - url: http://localhost:5000

paths:
  /:
    get:
      summary: Home Endpoint
      description: Returns a greeting message.
      responses:
        '200':
          description: Greeting message
          content:
            text/html:
              schema:
                type: string
                example: '<h1>Good Morning</h1>'

  /user/{user_id}:
    post:
      summary: Get User by ID
      description: Retrieve user information by user ID. Optionally filter fields.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user to retrieve.
          schema:
            type: integer
        - name: fields
          in: query
          required: false
          description: Comma-separated list of fields to return.
          schema:
            type: string
      responses:
        '200':
          description: User object
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  company:
                    type: string
                  email:
                    type: string
                  age:
                    type: integer
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: "User Not Found"

